//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageContent
    {
        public Nullable<int> MessageID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Subject { get; set; }
        public string ContentM { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
