//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageContents = new HashSet<MessageContent>();
        }
    
        public int MessageID { get; set; }
        public string Type { get; set; }
        public Nullable<bool> ReadM { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<MessageContent> MessageContents { get; set; }
    }
}
